src/pages/InterviewStatisticsPage/ui/InterviewStatisticsPage.module.css
src/pages/InterviewStatisticsPage/ui/InterviewStatisticsPage.tsx
src/shared/ui/AttemptInfoItem/ui/AttemptInfoItem.tsx
src/shared/ui/Block/ui/Block.tsx
src/widgets/Charts/index.ts
src/widgets/Charts/model/constants/options.ts
src/widgets/Charts/ui/ProgressByCategoriesItem/ProgressByCategoriesItem.module.css
src/widgets/Charts/ui/ProgressByCategoriesItem/ProgressByCategoriesItem.tsx
src/widgets/Charts/ui/ProgressByCategoriesList/ProgressByCategoriesList.module.css
src/widgets/Charts/ui/ProgressByCategoriesList/ProgressByCategoriesList.tsx

feat (YH-199) make a interview statistics page (part 3)

---

public/locales/en/profile.json
public/locales/ru/profile.json
src/entities/skill/model/types/skill.ts
src/entities/skill/ui/SkillSelect/SkillSelect.module.css
src/entities/skill/ui/SkillSelect/SkillSelect.tsx
src/entities/skill/ui/SkillsForm/SkillsForm.tsx
src/features/editProfileForm/model/lib/validation/profileSchema.ts

Add skill select to user profile form

---

src/entities/auth/api/__mocks__/data/mockProfileResponse.ts
src/pages/QuestionPage/ui/QuestionPage.tsx
src/widgets/Question/ui/AdditionalInfo/AdditionalInfo.module.css
src/widgets/Question/ui/AdditionalInfo/AdditionalInfo.tsx

При клике на кейворд отправляет на такой урл потому что не нашёл параметр котоый влияет на фильтр вопросов в целом, если есть то подскажите пожалуйста)

YH-318: question keywords section

---

src/app/layouts/MainLayout/ui/MainLayout.tsx
src/entities/socialNetwork/ui/SocialNetWorkList/SocialNetWorkList.tsx
src/widgets/Profile/ui/UserCard/ui/UserInfoBlock/UserInfoBlock.tsx

fix/YH-334 

---

src/features/theme/switch-theme/ui/ThemeSwitcher.tsx

Закомитил изменение темы  (°ー°〃)

YH-335 | Commit code for switch theme

---

src/widgets/PassedQuestions/ui/PassedQuestionsItem/PassedQuestionsItem.tsx

Не уверен, что правильно понял таску, жду комментарии

YH-371: change button to chip, interviewQuizResult

---

src/shared/ui/Card/ui/Card.module.css
src/shared/ui/Card/ui/Card.tsx

Настроил отображение блюра в свёрнутой карточке o((>ω< ))o

YH-405: Fix card-expand in Card module

---

config/webpack/webpackDevServer.ts
package.json

YH-413: Added webpackDevServer option to open application in specific browser

---

src/shared/ui/TextHtml/index.ts
src/shared/ui/TextHtml/ui/TextHtml.module.css
src/shared/ui/TextHtml/ui/TextHtml.tsx
src/widgets/Question/ui/QuestionBody/QuestionBody.tsx
src/widgets/Question/ui/QuestionPreview/QuestionPreview.tsx

- Wrap all content in <pre> tag
- Style code snippets
- Move component to shared/ui directory

YH-406: Refactored TextHtml component

---

src/app/styles/App.css
src/shared/helpers/getArrayFromTwoNumbers.ts
src/shared/ui/Pagination/ui/Pagination.module.css
src/shared/ui/Pagination/ui/Pagination.tsx

* Add helper function getArrayFromTwoNumbers
* Add missed text color var in App.css
* Changed Pagination styles
* Improved Pagination logic

YH-215: Pagination refactoring

---

src/shared/ui/Card/ui/Card.module.css
src/shared/ui/Card/ui/Card.tsx

Внес изменения в стиль карточки (°ー°〃)

YH-415: Fix card styles

---

package-lock.json
package.json
src/app/styles/App.css
src/shared/config/i18n/i18nTranslations.ts
src/shared/ui/TextHtml/ui/TextHtml.module.css

YH-456: update uikit to latest, fix i18n merge error, update code teg  style

---

src/app/providers/router/config/routeConfig.tsx
src/pages/interview/QuestionPage/ui/QuestionPage.module.css
src/pages/interview/QuestionPage/ui/QuestionPage.tsx
src/shared/config/router/routes.ts
src/widgets/QuestionsTable/ui/QuestionsTable.tsx

https://tracker.yandex.ru/YH-424

YH-424: admin QuestionDetailPage implementation

---

public/index.html
src/app/styles/App.css
src/features/theme/switch-theme/model/types/themeProvider.ts
src/features/theme/switch-theme/ui/ThemeSwitcher.tsx
src/features/theme/switch-theme/utils/initTheme.ts
src/features/theme/switch-theme/utils/themeUtils.ts

fixed files:
index.html
App.css
themeProvider.ts
ThemeSwitcher.jsx
themeUtils.ts
initTheme.ts

YH-457: commented dark theme

---

public/locales/en/profile.json
public/locales/ru/profile.json
src/features/profile/changePassword/index.ts
src/features/profile/changePassword/ui/ChangePassword.module.css
src/features/profile/changePassword/ui/ChangePassword.tsx
src/pages/profile/SettingsProfilePage/ui/SettingsProfilePage.tsx
src/shared/config/i18n/i18nTranslations.ts
src/widgets/Profile/index.ts
src/widgets/Profile/ui/ChangePasswordTab/index.ts
src/widgets/Profile/ui/ChangePasswordTab/model/lib/validation/changePasswordSchema.ts
src/widgets/Profile/ui/ChangePasswordTab/model/types/changePasswordSchemaTypes.ts
src/widgets/Profile/ui/ChangePasswordTab/ui/ChangePasswordTab.tsx

add translation for Change Password, add form Change Password, add validation for form

YH-515: add Tab Change Password

---

src/widgets/Charts/model/constants/options.ts
src/widgets/Charts/ui/PassedQuestionChart/PassedQuestionChart.tsx

ломалось из-за свойства pointer.show причину не понял, но именно когда свойство вычисляемое ломалось а если оно статичное допустим всегда true то все будет ок

YH-526: del pointer.show options.gauge.

---

src/app/layouts/AuthLayout/ui/AuthLayout/AuthLayout.tsx
src/app/layouts/MainLayout/ui/MainLayout.tsx
src/shared/helpers/formatAddress.tsx
src/shared/ui/ErrorBoundary/index.ts
src/shared/ui/ErrorBoundary/ui/ErrorBoundary.tsx
src/shared/ui/ErrorElement/ui/ErrorElement.module.css
src/shared/ui/ErrorElement/ui/ErrorElement.tsx
src/shared/ui/KeywordInput/KeywordInput.tsx
src/widgets/Profile/ui/UserCard/ui/UserInfoBlock/UserInfoBlock.tsx

добавлен ErrorBoundary на AuthLayout и MainLayout
formatAddress - создавала вложенность тегов ЛИ что вызывало ошибку

YH-531: add ErrorBoundary; refactor formatAddress function

---

src/shared/ui/Modal/ui/Modal.tsx

Fix/yh 557 fix: buttons size, bound modalRef with the modal

---

src/entities/profile/ui/EmailVerify/EmailVerify.module.css

YH-580: fixed email verify stumb height

---

src/app/providers/router/ui/InterviewRoute.tsx
src/app/providers/router/ui/VerifiedEmailRoute.tsx
src/entities/auth/api/authApi.ts
src/entities/profile/index.ts
src/entities/profile/model/selectors/profileSelectors.ts
src/entities/profile/model/slices/profileSlice.ts
src/entities/profile/model/types/profile.ts
src/features/profile/changePassword/ui/ChangePassword.tsx
src/features/profile/confirmationEmail/ui/ConfirmationEmail.tsx
src/pages/admin/QuestionEditPage/ui/QuestionEditPage.tsx
src/pages/admin/QuestionPage/QuestionPage.tsx
src/pages/auth/LoginPage/ui/LoginPage.tsx
src/pages/interview/InterviewQuizPage/ui/InterviewQuizPage.tsx
src/pages/interview/InterviewQuizResultPage/ui/InterviewQuizResultPage.tsx
src/pages/interview/InterviewStatisticsPage/ui/InterviewStatisticsPage.tsx
src/pages/interview/MainPage/ui/MainPage.tsx
src/pages/interview/QuestionPage/ui/QuestionPage.tsx
src/pages/interview/QuestionsPage/ui/QuestionsPage/QuestionsPage.tsx
src/pages/profile/ProfilePage/ui/ProfilePage.tsx
src/widgets/FullInterviewHistory/ui/FullInterviewHistoryList/model/hooks/useGetHistory.ts
src/widgets/IncompleteProfileStub/ui/IncompleteProfileStub.tsx
src/widgets/InterviewHistory/ui/InterviewHistoryList/InterviewHistoryList.tsx
src/widgets/InterviewQuestions/ui/InterviewQuestionsList/InterviewQuestionsList.tsx
src/widgets/Question/ui/QuestionActions/QuestionActions.tsx
src/widgets/Question/ui/QuestionPreview/QuestionPreview.tsx

пробовала тип ProfileResponse импортировать через нотацию @x, но все равно линтеры подсвечивали красным.

YH-538: useProfileQuery replacement

---

public/locales/en/translation.json
public/locales/ru/translation.json
src/features/profile/editProfileForm/ui/EditProfileForm/EditProfileForm.tsx
src/features/question/createQuestion/ui/QuestionCreateForm/QuestionCreateForm.tsx
src/features/question/editQuestion/ui/QuestionEditForm/QuestionEditForm.tsx
src/features/skill/createSkill/ui/SkillCreateForm/SkillCreateForm.tsx
src/features/skill/editSkill/ui/SkillEditForm/SkillEditForm.tsx
src/features/specialization/createSpecialization/ui/SpecializationCreateForm/SpecializationCreateForm.tsx
src/features/specialization/editSpecialization/ui/SpecializationEditForm/SpecializationEditForm.tsx
src/shared/ui/Breadcrumbs/ui/Breadcrumbs.tsx

По задаче изменил, текст и добавил модальные окна, если введённые данные небыли сохранены(формы админки)
Так же исправил проблему, с редактированием профиля

YH-219: feature:model for admin form. fix: modal editProfile

---

.github/workflows/deploy.yml

* fix deploy action
* add branch target for develop
---------

Fix/ci cd deploy (#360)

---

src/shared/ui/Tabs/ui/Tabs.test.tsx
src/shared/ui/Tabs/ui/Tabs.tsx

- Add test for component Tabs
1. Renders active tab correctly on initial render.
2. Applies correct line position and width.
3. Updates active tab and line position on tab click.
4. Navigates to the correct tab when clicked.
5. Renders title if provided.
6. Handles empty tabs array gracefully.

YH-630: add test for Tabs

---

src/app/layouts/MainLayout/ui/MainLayout.module.css
src/app/layouts/MainLayout/ui/MainLayout.skeleton.tsx
src/shared/ui/AppLogo/AppLogo.skeleton.tsx
src/widgets/Header/ui/Header.module.css
src/widgets/Header/ui/Header.skeleton.tsx
src/widgets/Sidebar/ui/Sidebar/Sidebar.module.css
src/widgets/Sidebar/ui/Sidebar/Sidebar.skeleton.tsx

https://tracker.yandex.ru/YH-620

[fix/YH-620] - [platform] Скелетон для mainlayout на мобилке

---

src/app/msw/handlers.ts
src/features/specialization/editSpecialization/api/__mocks__/index.ts
src/features/specialization/editSpecialization/api/__mocks__/specializationEditMock.ts
src/features/specialization/editSpecialization/index.ts

- Сделан моковый запрос на изменение специализации.

YH-719: Add mock request for  edit specialization

---

src/pages/interview/InterviewPage/ui/InterviewPage.module.css
src/shared/ui/Chip/ui/Chip.module.css
src/shared/ui/ImageWithWrapper/ui/ImageWithWrapper.module.css
src/shared/ui/TextHtml/ui/TextHtml.tsx
src/shared/ui/charts/PieChart/ui/PieChart/PieChart.tsx
src/shared/ui/charts/PieChart/ui/PieSegmentList/PieSegmentList.module.css
src/shared/ui/charts/PieChart/ui/PieSegmentList/PieSegmentList.tsx
src/widgets/Landing/InterviewBlock/ui/AdvantagesList/AdvantagesList.module.css
src/widgets/Landing/InterviewBlock/ui/InterviewBlock/InterviewBlock.module.css
src/widgets/Landing/InterviewModeBlock/ui/InterviewModeBlock/InterviewModeBlock.module.css
src/widgets/Landing/PlatformInterfaceBlock/ui/PlatformInterfaceBlock/PlatformInterfaceBlock.module.css
src/widgets/interview/PassedQuizzesList/ui/InterviewParameters/InterviewParameters.module.css
src/widgets/interview/PassedQuizzesList/ui/QuestionCategores/QuestionCategories.module.css
src/widgets/question/QuestionsList/ui/PreviewQuestionsItem/PreviewQuestionsItem.tsx

Пофиксил "залипание" кнопки фильтров(специализации/навыков и тд) , поправил адаптацию под мобильное разрешение по макету нескольких блоков,а именно : Карточки результата собеседований,истории собеседований,так же внес небольшие правки по макету дашборда/лендинга

YH-798: Fix button and block styles on dashboard and landings

---

src/entities/skill/api/__mocks__/index.ts
src/entities/skill/api/__mocks__/skillEditMock.ts
src/entities/skill/api/__mocks__/skillMock.ts
src/entities/skill/model/types/skill.ts
src/shared/ui/Chip/ui/Chip.module.css

Добавил моковый patch запрос(и типы для него) на изменение навыка,так же исправил ошибку которую нашел,из-за которой моковый запрос на получения навыка по айди не работал(из-за дублирования кода)

YH-722: Add mock request for edit skill

---

src/pages/admin/QuestionPage/QuestionPage.tsx
src/pages/interview/QuestionPage/ui/QuestionPage.tsx
src/pages/landing/PublicQuestionPage/ui/PublicQuestionPage.tsx
src/shared/ui/Card/ui/Card.tsx
src/shared/ui/TextHtml/ui/TextHtml.module.css
src/shared/ui/TextHtml/ui/TextHtml.tsx

Исправил наложение кнопки "Скрыть" на текст.Исправил стили для текста вопросов.Добавил оверфлоу для мобильных версий вопросов.

YH-823: Fix questions text style and add mobile overflow

---

src/shared/ui/AppLogo/AppLogo.tsx

Теперь текст логотипа не рендерится при закрытом сайдбаре.

YH-843: hide text logo with close sidebar

---

src/entities/collection/api/__mock__/data/collectionsMock.ts
src/entities/question/api/__mocks__/data/questionsMock.ts
src/entities/question/index.ts
src/entities/question/model/types/question.ts
src/entities/question/ui/QuestionAuthor/QuestionAuthor.tsx
src/features/question/createQuestion/api/__mocks__/data/newQuestionMock.ts
src/widgets/Profile/ui/UserCard/ui/UserImageBlock/UserImageBlock.tsx
src/widgets/question/QuestionAdditionalInfo/ui/QuestionAdditionalInfo.tsx

Поправил отображение аватара автора вопроса.
Параллельно возникла необходимость изменения типа и логики createdBy в компоненте QestionAuthor, т.к после изменения типа на бэке пропала ссылка на автора вопроса.
Пока что сделал отдельный тип Author для данного кейса.

YH-921: Fix incorrect author avatar and link logic

---

src/pages/interview/CollectionsPage/ui/CollectionsPage/CollectionsPage.module.css
src/pages/interview/CollectionsPage/ui/CollectionsPage/CollectionsPage.tsx

Создал кнопку открытия фильтров на странице коллекций

YH-910: added filters button

---

src/entities/collection/ui/CollectionForm/CollectionForm.tsx
src/entities/question/ui/ChooseQuestionsDrawer/ChooseQuestionsDrawer.tsx
src/entities/specialization/ui/SpecializationSelect/SpecializationSelect.tsx

Исправлена ошибка добавления вопросов в коллекцию (при добавлении вопросов в коллекцию почему то попадались вопросы других специальностей)
Добавил фильтрация вопросов в ChooseQuestionsDrawer по выбранным специализациям при создании/редактировании коллекции. Передаю specializations из CollectionForm в ChooseQuestionsDrawer и использую их в useGetQuestionsListQuery через параметр specialization.

YH-924: fix adding questions in collection

---

src/entities/quiz/api/quizApi.ts

Изменение значения поля mode, для получения всех вопросов при создании квиза, в том числе изученных.

YH-923: get all questions when creating new quiz

---

src/shared/ui/Calendar/EventCalendar.skeleton.module.css
src/shared/ui/Calendar/EventCalendar.skeleton.tsx

Добавил стили для скелетона календаря

YH-902: Fix calendar skeleton layout

---

src/pages/interview/CollectionsPage/ui/CollectionsPage/CollectionsPage.tsx

Исправление загрузки коллекций. Теперь коллекции загружаются с id специализации из профиля.

YH-950: Fix collections list

---

src/pages/interview/MainPage/ui/MainPage.module.css

Исправление некорректных размеров блоков MainPage в user-unverified

YH-946: Fix size of MainPage blocks in unverified profile

---

src/features/collections/trainCollection/ui/TrainCollectionButton.tsx

Увеличил лимит вопросов тренажера коллекций

YH-964: Fix collection training questions limit

---

src/pages/interview/CollectionPage/ui/CollectionPage.module.css
src/pages/interview/CollectionPage/ui/CollectionPage.tsx

При клике на подробности о коллекции открывается вместо поповера шторка

YH-952: Change popover to drawer in Collection

---

src/entities/question/ui/ChooseQuestionsCategories/ChooseQuestionsCategories.tsx
src/pages/interview/CreateQuizPage/ui/CreateQuizPage.tsx

Удалил аккордеон категорий на странице создания квиза, показываются все навыки

YH-965: Remove show all categories label from quiz creating

---

src/app/layouts/MainLayout/model/helper/SkeletonGenerator.tsx
src/pages/admin/CollectionsPage/index.ts
src/pages/admin/CollectionsPage/ui/CollectionsPage/CollectionsPage.skeleton.tsx
src/pages/admin/CompaniesTablePage/index.ts
src/pages/admin/CompaniesTablePage/ui/CompaniesTablePage/CompaniesTablePage.skeleton.tsx
src/pages/admin/QuestionsTablePage/index.ts
src/pages/admin/QuestionsTablePage/ui/QuestionsTablePage/QuestionsTablePage.skeleton.tsx
src/pages/admin/SkillsPage/index.ts
src/pages/admin/SkillsPage/ui/SkillsPage/SkillsPage.skeleton.tsx
src/pages/admin/SpecializationsPage/index.ts
src/pages/admin/SpecializationsPage/ui/SpecializationsPage/SpecializationsPage.skeleton.tsx
src/pages/admin/UserTablePage/index.ts
src/pages/admin/UserTablePage/ui/UserTablePage/UsersTablePage.skeleton.tsx
src/shared/config/router/routes.ts
src/shared/ui/Checkbox/Checkbox.skeleton.tsx
src/shared/ui/Checkbox/index.ts
src/shared/ui/Table/Table.skeleton.tsx
src/shared/ui/Table/index.ts

- Добавил скелетон для таблиц.
- Исправил путь /admin/users

YH-951: add table skeleton, fix /admin/user route

---

src/shared/hooks/useQueryFilter.ts
src/shared/ui/FiltersDrawer/FiltersDrawer.module.css
src/shared/ui/FiltersDrawer/FiltersDrawer.tsx

изменил источник данных о фильтрах и добавил cursor pointer

YH-976: fixed FiltersDrawer.tsx state and button's cursor style

---

src/features/profile/editProfileForm/ui/EditProfileForm/EditProfileForm.module.css
src/shared/ui/Table/Table.module.css

Исправила баг со стилями: глобальный селектор section * из EditProfileForm ломал отображение таблиц

YH-969: Fix paddings in Table

---

src/pages/admin/SpecializationsPage/ui/SpecializationsPagePagination/SpecializationPagePagination.module.css

Исправлено позиционирование пагинации в таблице специализаций

YH-970: Fix position of pagination in admin/specializations

---

src/entities/collection/ui/CollectionPreview/CollectionPreview.tsx

Исправлен путь при клике на карточку публичной коллекции

YH-993: Fix public collection route

---

src/entities/question/ui/QuestionForm/QuestionForm.module.css
src/entities/question/ui/QuestionForm/QuestionForm.tsx

- change Text component from yeahub-ui-kit to Text from shared/ui
- delete styles '.label' from css because its not needed yet
- change color for labels to black-800 like in Figma

YH-974: add Text from shared/ui for QuestionForm

---

src/pages/landing/PublicQuestionsPage/ui/PublicQuestionsPage/PublicQuestionsPage.module.css

Изменил ширину блока с фильтрами на фиксированную, аналогично такой же странице в dashboard

YH-994: fix filters width

---

src/widgets/CollectionsTable/ui/CollectionsTable.tsx
src/widgets/CompaniesTable/ui/CompaniesTable.tsx
src/widgets/QuestionsTable/ui/QuestionsTable.tsx
src/widgets/SkillsTable/ui/SkillsTable.tsx
src/widgets/SpecializationsTable/ui/SpecializationsTable.tsx
src/widgets/UsersTable/ui/UsersTable.tsx

- Обернул названия и похожие столбцы по логике (где нет столбца "название") в Link. Сослался на функцию route для формирования url.
- Добавил обёртку Text с необходимыми пропсами

YH-977: added navigation by title text click and styles for text

---

src/shared/config/api/baseApi.ts

Проблема:
При долгом отсутствии пользователя в системе (просроченные токены) после возвращения требовалось двукратное обновление страницы, чтобы получить актуальный профиль. Первый запрос за профилем возвращал 401 (Unauthorized), так как токен был невалиден. После этого система отправляла запрос на обновление токенов, но новый access_token приходил слишком поздно, и профиль не отображался.
Исправления:
1. Добавил логику в baseQueryWithReauth, которая при получении 401 автоматически инициирует запрос на обновление токена.
Если обновление токена успешно, новый access_token сохраняется в localStorage.
2. После успешного обновления токена автоматически повторяется исходный запрос за профилем, что позволяет пользователю сразу увидеть актуальные данные.

YH-1007: fix auth token update

---

src/pages/admin/CollectionsPage/model/selectors/collectionsPageSelectors.ts
src/pages/admin/CollectionsPage/model/slices/collectionsPageSlice.ts
src/pages/admin/CollectionsPage/model/types/collectionsPageTypes.ts
src/pages/admin/CollectionsPage/ui/CollectionsPage/CollectionsPage.tsx

- подключил селектор getCollectionsSearch
- добавил titleOrDescriptionSearch к получаемой data из useGetCollectionsListQuery
- написал функцию onChangeSearch в которой диспачу value
- прокинул  onChangeSearch в атрибут onSearch компонента SearchSection

YH-979: fix search in CollectionsPage

---

src/entities/guru/ui/GuruSocialsList/GuruSocialsList.module.css
src/entities/guru/ui/GuruSocialsList/GuruSocialsList.tsx
src/shared/ui/Flex/Flex.module.css
src/shared/ui/Flex/Flex.tsx
src/widgets/Profile/ui/UserCard/ui/UserBlock/UserBlock.module.css
src/widgets/Profile/ui/UserCard/ui/UserBlock/UserBlock.tsx
src/widgets/Profile/ui/UserCard/ui/UserInfoBlock/UserInfoBlock.tsx

Исправлено некорректное отображение ролей в профиле

YH-1025: Fix profile roles view

---

public/locales/en/translation.json
public/locales/ru/translation.json
src/app/providers/router/config/routeConfig.tsx
src/app/styles/App.css
src/shared/config/i18n/i18nTranslations.ts
src/widgets/Header/ui/UserPreferences/UserPreferences.tsx

1. Delete the "Settings" link from the sidebar
2. Add 'Choose membership' and 'Settings' links to the profile popover.
3. Delete the "Change password" link from the popover profile

YH-1026: Update sidebar and popover profile links

---

src/pages/interview/CollectionPage/ui/CollectionPage.tsx
src/widgets/Collection/ui/CollectionBody/CollectionBody.tsx

CollectionPage got a role in CollectionPage and transferred it to CollectionBody. Added an optional check for the role.

YH-735: Added an optional check for the role in CollectionBody.

---

src/widgets/question/QuestionsList/ui/PreviewQuestionsList/PreviewQuestionsList.tsx

Добавлена обертка для заглушки вопросов

YH-1050: Add a wrapper to stub questions

---

src/entities/user/ui/UserEditButton/UserEditButton.tsx
src/shared/ui/AvatarWithoutPhoto/AvatarWithoutPhoto.module.css
src/shared/ui/ImageLoader/ImageLoader.module.css
src/widgets/Profile/ui/UserCard/ui/UserBlock/UserBlock.module.css
src/widgets/Profile/ui/UserCard/ui/UserImageBlock/UserImageBlock.module.css
src/widgets/Profile/ui/UserCard/ui/UserInfoBlock/UserInfoBlock.module.css
src/widgets/Profile/ui/UserCard/ui/UserInfoBlock/UserInfoBlock.tsx

1. Кнопка "Редактировать" во всех разрешениях теперь только карандаш
2. Мобильная версия начинается с <768px
3. Заменены все компоненты с текстом на Text

YH-1044: Profile correction

---

src/app/index.tsx
src/app/layouts/MainLayout/ui/MainLayout.tsx
src/app/providers/router/config/routeConfig.tsx
src/app/providers/sentry/AppInitSentryUser.tsx
src/app/providers/store/config/config.ts
src/shared/config/sentry/ErrorBoundary.tsx
src/shared/config/sentry/SentryRouteTracker.tsx
src/shared/config/sentry/appContext.ts
src/shared/config/sentry/context.ts
src/shared/config/sentry/middleware.ts
src/shared/config/sentry/sentry.ts
src/shared/config/sentry/sentryApiErrorMiddleware.ts

Что доработано из функционала Sentry:
1. Централизованный сбор ошибок:
- Все ошибки React-компонентов, глобальные JS-ошибки и ошибки API автоматически отправляются в Sentry.
2. User Feedback (Bug report):
- Форма обратной связи появляется только при ошибке (автоматически через showReportDialog), сообщения попадают в User Feedback в Sentry.
3. User context:
- В ошибках отображается информация о пользователе (id, email, роль), если он авторизован.
4. Breadcrumbs:
- В ошибках есть breadcrumbs ключевых действий пользователя (redux actions, роутинг).
5. Session replay и performance monitoring:
Включены и настроены.
6. Безопасность:
- beforeSend фильтрует чувствительные данные (пароли, токены, cookies и т.д.).
Нужно потестировать, поиграться. Я локально потестил, вроде бы всё ок из того что …

YH-986: update sentry setting & reports

---

src/app/styles/normalize.css

1. Fix links styles
2. Delete duplicate in normolize.css in 'abbr[title]' tag

YH-11: fix link styles

---

src/shared/constants/customRoutes.ts
src/widgets/Collection/ui/CollectionBody/CollectionBody.tsx
src/widgets/Header/ui/UserPreferences/UserPreferences.tsx
src/widgets/interview/InterviewPreparation/ui/InterviewPreparation/InterviewPreparation.tsx
src/widgets/interview/PassedQuizzesList/ui/PreviewPassedQuizzesList/PreviewPassedQuizzesList.tsx
src/widgets/interview/QuestionsStatistic/ui/PreviewQuestionsStatistic/PreviewQuestionsStatistic.tsx

Исправлена ссылка выбора тарифа из коллекции

YH-1190: fix incorrect link to settings page

---

src/features/profile/changePassword/ui/ChangePassword.module.css
src/features/profile/changePassword/ui/ChangePassword.tsx
src/shared/ui/FormControl/FormControl.tsx

-Заменила теги p и h3 на компонент текста
-Исправила наложение стилей на лейбл и лейбл ошибки

YH-1163: fix input label and error label

---

src/features/authentication/forgotPassword/ui/EmailSendModal/EmailSendModal.module.css
src/features/authentication/forgotPassword/ui/EmailSendModal/EmailSendModal.tsx
src/features/authentication/login/ui/LoginForm/LoginForm.module.css
src/features/authentication/login/ui/LoginForm/LoginForm.tsx
src/features/authentication/login/ui/RegistrationLabel/RegistrationLabel.tsx
src/features/authentication/registration/ui/LoginLabel/LoginLabel.tsx
src/features/authentication/registration/ui/RegisterForm/RegisterForm.module.css
src/features/authentication/registration/ui/RegisterForm/RegisterForm.tsx
src/features/authentication/socialAuthenticate/SocialAuthenticateList/ui/SocialAuthenticateList.module.css
src/features/authentication/socialAuthenticate/SocialAuthenticateList/ui/SocialAuthenticateList.tsx

поменял отступ в тексте ошибка валидации формы, прилипала к левому краю формы

YH-1206: fix left margin

---

src/shared/ui/GradeChip/GradeChip.test.tsx
src/shared/ui/GradeChip/GradeChip.tsx

https://tracker.yandex.ru/YH-867

YH-867: adding tests for the component

---

src/pages/admin/CollectionPage/ui/CollectionPage.tsx
src/widgets/Collection/ui/CollectionBody/CollectionBody.tsx

- для админа сняты ограничения по отображению контента
- админ теперь видит все вопросы коллекции

YH-1213: display all questions without restrictions for admin

---

src/shared/ui/TextEditor/TextEditor.tsx

добавлен кастомный класс для контейнера ProseMirror через editorProps

YH-1214: expanded clickable area of Tiptap editor

---

src/entities/profile/index.ts
src/entities/profile/model/selectors/profileSelectors.ts
src/features/collections/editCollection/ui/CollectionEditForm/CollectionEditForm.tsx
src/pages/admin/CollectionEditPage/ui/CollectionEditPage.tsx
src/pages/admin/CollectionPage/ui/CollectionPage.tsx
src/pages/admin/CollectionsPage/ui/CollectionsPage/CollectionsPage.tsx

В админке/коллекциях теперь юзер с ролью: 'admin' может редатировать и удалять колекции, как на странице всех коллекций, так и на странице конкретной коллекции.

YH-367: fixed editing and deleting collection by admin

---

src/entities/subscription/model/types/subscription.ts
src/widgets/Profile/ui/SubscriptionTab/ui/PremiumSubscriptionTab/PremiumSubscriptionTab.tsx

Добавление проверки состояния подписки

YH-1260: fix title changes when subscription is cancelled

---

src/features/subscriptions/subscribe/ui/AgreementForm/AgreementForm.tsx
src/features/subscriptions/trial/api/getTrial.ts
src/shared/ui/Tabs/hooks.ts

- изменила инвалидацию тегов в trialApi, в результате - интерфейс обновляется
- по поводу редиректа на соседнюю вкладку, использовала useEffect, чёт ничего другого на ум не пришло
- есть изменения в AgreementForm, т.к. видимо проводился рефакторинг и после того, как я подтянула актульную develop, TrialButton в этом файле не оказалось

YH-1287: update interface after successful activation trial subscription

---

src/entities/company/model/types/companyTypes.ts
src/entities/company/ui/CompanyForm/CompanyForm.tsx
src/features/company/editCompany/model/lib/validation/companyEditSchema.ts

Кнопка сохранить теперь работает, поля сделал необязательными

YH-1292: Fix edit form button

---

src/entities/question/index.ts
src/entities/question/model/lib/getQuestionImage.ts
src/widgets/question/QuestionHeader/ui/QuestionHeader.tsx
src/widgets/question/QuestionsList/ui/PreviewQuestionsItem/PreviewQuestionsItem.tsx

Добавил отображение изображение навыков на страницах указанных. 
Подправил импорт, сделал все в одном.

YH-1296: added show to image skill in question

---

src/shared/ui/Card/Card.module.css

Добавил переносы слов при превышении границы

YH-1283: Add break-word rule in Card.module.css

---

src/entities/socialNetwork/ui/SocialNetWorkList/SocialNetWorkList.tsx

Исправил дублирование иконок соцсетей после редактирования

YH-1284: fix unique key

---

src/app/layouts/LandingLayout/model/helper/SkeletonGenerator.tsx
src/entities/collection/ui/CollectionPreview/CollectionPreview.sekeleton.tsx
src/pages/landing/LandingPage/ui/LandingPage.skeleton.tsx
src/widgets/Landing/CollectionBlock/index.ts
src/widgets/Landing/CollectionBlock/ui/AdditionalBlock/AdditionalBlock.skeleton.tsx
src/widgets/Landing/CollectionBlock/ui/CollectionBlock/CollectionBlock.skeleton.tsx
src/widgets/Landing/CollectionBlock/ui/FilterChip/FilterChip.skeleton.tsx
src/widgets/Landing/CollectionBlock/ui/FiltersBlock/FiltersBlock.skeleton.tsx
src/widgets/Landing/CollectionBlock/ui/MainBlock/MainBlock.skeleton.tsx

Доделал скелетон для лендинга и подключил его

YH-1000: add skeleton to collection block, connect skeleton to landing page

---

src/shared/ui/Text/Text.test.tsx

YH-875: add tests to Text component

---

src/app/msw/handlers.ts
src/entities/collection/api/__mock__/collectionListMock.ts
src/entities/collection/api/__mock__/data/collectionsMock.ts
src/entities/collection/api/__mock__/index.ts
src/entities/collection/index.ts

добавлен моковый запрос для получения списка коллекций и публичных коллекций

YH-1327: add mock request to fetch collections list

---

src/entities/collection/ui/CollectionPreview/CollectionPreview.tsx

В компоненте CollectionPreview.tsx исправил ссылку, теперь переход на саму коллекцию происходит по нажатию на любую часть карточки коллекции, а не только по изображению.

YH-1328: fix in CollectionPreview wrapped the collection in a Link

---

src/features/profile/editProfileForm/model/lib/helpers/editProfileFormHelpers.ts
src/features/profile/editProfileForm/model/lib/validation/editProfileSchema.ts
src/features/profile/editProfileForm/ui/PersonalInfoFields/PersonalInfoFields.tsx

На странице редактирования профиля сделал поле ввода email'а необязательным.

YH-1351: made the name field in the profile optional

---

src/shared/ui/Icon/icons.ts
src/shared/ui/Icon/types.ts
src/widgets/interview/PassedQuestionsList/ui/PassedQuestionsItem/PassedQuestionsItem.module.css
src/widgets/interview/PassedQuestionsList/ui/PassedQuestionsItem/PassedQuestionsItem.tsx
src/widgets/interview/PassedQuestionsList/ui/PassedQuestionsList/PassedQuestionsList.module.css

Обновил виджет пройденных вопросов собеседования.

YH-1333: updated the widget for completed interview questions

---

src/widgets/Marketplace/model/hooks/useMarketplaceFilters.ts

Reset skills on specialization change
Public Resources Page (file: src/widgets/Marketplace/model/hooks/**useMarketplaceFilters.ts‎**)

YH-1385: Fix reset skills

---

public/locales/en/profile.json
public/locales/en/translation.json
public/locales/ru/profile.json
public/locales/ru/translation.json
src/features/authentication/telegramLink/api/telegramLinkApi.ts
src/shared/config/i18n/i18nTranslations.ts

YH-1391: Fix translation bugs
